// This file is generated by SQLBoiler (https://github.com/volatiletech/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	Invoices        string
	Persons         string
	Tags            string
	TransactionTags string
	Transactions    string
	Units           string
}{
	Invoices:        "invoices",
	Persons:         "persons",
	Tags:            "tags",
	TransactionTags: "transaction_tags",
	Transactions:    "transactions",
	Units:           "units",
}
